language: go

go:
  - 1.11.x
  - 1.12.x
  - 1.13.x

services:
  - mysql
  - postgresql

# Setting sudo access to false will let Travis CI use containers rather than
# VMs to run the tests. For more details see:
# - http://docs.travis-ci.com/user/workers/container-based-infrastructure/
# - http://docs.travis-ci.com/user/workers/standard-infrastructure/
sudo: false

install:
  - go get -t -tags integration
  - go install github.com/mattn/go-sqlite3 # Precompile so test timing is accurate

before_script:
  - mysql -e 'CREATE DATABASE squirrel;'
  - psql -c 'CREATE DATABASE squirrel;' -U postgres

script:
  - go test -tags integration -args -driver sqlite3
  - go test -tags integration -args -driver mysql -dataSource travis@/squirrel
  - go test -tags integration -args -driver postgres -dataSource 'postgres://postgres@localhost/squirrel?sslmode=disable'

notifications:
  irc: "irc.freenode.net#masterminds"
